# detectors:
#   cpu:
#     type: cpu
#     num_threads: 4
#     model:
#       path: "/cpu_model.tflite"
  # tensorrt:
  #   type: tensorrt
  #   device: 0 #This is the default, select the first GPU

# model:
#   path: /config/model_cache/tensorrt/yolov7-320.trt
#   input_tensor: nchw
#   input_pixel_format: rgb
#   width: 320
#   height: 320

# ffmpeg:
#   hwaccel_args: -hwaccel_output_format yuv420p -c:v h264_nvmpi
#   input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
#   output_args:
#     record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy

#No tocar sin saber
mqtt:
  enabled: false
  host: rabbitmq
  user: "guest"
  password: "guest" 
  client_id: "store_01" #Identifica la maquina  

# Detecciones
detect: 
  # Cuantas detecciones por segundo por camara
  fps: 5
  enabled: True
  # Cuantas frames tiene que faltar el objeto para considerarse desaparecido 
  max_disappeared: 1
  height: 640 #576
  width: 640 #704
  stationary:
      interval: 1
      threshold: 100
      max_frames:
        # Optional: Object specific values
        objects:
          person: 1000

# Objetos filtro por objetos
objects:
      track:
        - person
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 1000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.3
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.5
      

# Grabaciones de eventos
record:
  # Guardamos todos los videos?.
  enabled: True
  # Cada cuanto nos fijamos si hay que borrar algun video viejo ocupando espacio?
  expire_interval: 10
  retain: 
    days: 0
    mode: active_objects
  events: 
    retain:
      default: 10
      mode: active_objects

motion:
    threshold: 50 
    contour_area: 50
           
#Camaras 
cameras:

  G1V:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.63
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 0,0,640,0,640,446,0,444
        - 0,640,640,640,640,555,296,560,0,528
        - 640,640,640,0,484,0,490,555

  G2V:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.75
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 0,0,640,0,640,443,0,448
        - 0,640,640,640,640,530,324,560,0,536

  G3V:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.56
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 0,0,640,0,640,441,0,436
        - 0,640,640,640,640,539,308,556,0,539

  G4F:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.45
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 640,0,640,106,0,65,0,0
        - 640,206,640,640,0,640,107,172

  G4V:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.64
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 0,0,640,0,640,293,0,296
        - 0,640,640,640,640,416,202,412

  G5F:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.89
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 0,0,640,0,640,59,0,86
        - 0,640,640,640,640,156,0,201

  G5V:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.53
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 0,0,640,0,640,333,0,342
        - 0,640,640,640,640,417,0,420
        - 459,0,640,0,640,416,472,427
    
  G6F:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.74
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 640,0,640,85,0,82,0,0
        - 640,0,387,0,550,640,640,640
        - 0,640,640,640,640,182,0,190

  G6V:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.67
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 0,0,640,0,640,385,0,385
        - 640,588,640,0,422,0,452,461
        - 0,640,640,640,640,471,0,460
    
  G7V:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.68
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 0,0,640,0,640,440,0,412
        - 0,0,155,0,149,533,0,584
        - 640,565,640,640,0,640,0,566,147,535

  G8V:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.44
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 0,0,640,0,640,508,305,568,0,532

  G9V:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.77
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 401,0,640,0,640,640,553,640,440,610,433,502
        - 0,0,640,0,640,489,0,491

  G10V:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.88
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 0,0,0,522,167,591,173,229
        - 144,0,640,0,640,473,161,474
        - 330,471,154,464,158,618

  G11V:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.87
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 0,0,640,0,640,430,0,606

  G12V:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.61
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 0,0,640,0,640,482,0,482
        - 640,640,640,579,306,619,0,595,0,640
  
  G13V:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.50
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      threshold: 50
      mask:
        - 0,640,337,640,212,23,0,0
        - 75,640,640,640,640,384,51,253
        - 589,0,571,288,196,262,202,0

# Detectores
#detectors:
#  cpu1:
#    type: cpu
#    num_threads: 3

detectors:
  ov1:
    type: openvino
    device: AUTO
    num_threads: 4
    model:
      path: /yolov8/yolov8m_tracking_pilar_11cam.xml 
  ov2:
    type: openvino
    device: AUTO
    num_threads: 4
    model:
      path: /yolov8/yolov8m_tracking_pilar_11cam.xml
  
      
# Modelos
model:
  width: 640 #416 #704
  height: 640 #416
  input_tensor: nchw #nchw
  input_pixel_format: rgb #bgr #rgb
  model_type: yolov8
  labelmap:
    0: person





