# detectors:
#   cpu:
#     type: cpu
#     num_threads: 4
#     model:
#       path: "/cpu_model.tflite"
  # tensorrt:
  #   type: tensorrt
  #   device: 0 #This is the default, select the first GPU

# model:
#   path: /config/model_cache/tensorrt/yolov7-320.trt
#   input_tensor: nchw
#   input_pixel_format: rgb
#   width: 320
#   height: 320

# ffmpeg:
#   hwaccel_args: -hwaccel_output_format yuv420p -c:v h264_nvmpi
#   input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
#   output_args:
#     record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy

#No tocar sin saber
mqtt:
  enabled: false
  host: rabbitmq
  user: "guest"
  password: "guest" 
  client_id: "store_01" #Identifica la maquina  

# Detecciones
detect: 
  # Cuantas detecciones por segundo por camara
  fps: 5
  enabled: True
  # Cuantas frames tiene que faltar el objeto para considerarse desaparecido 
  max_disappeared: 1
  height: 640 #576
  width: 640 #704
  stationary:
      interval: 1
      threshold: 100
      max_frames:
        # Optional: Object specific values
        objects:
          person: 1000

# Objetos filtro por objetos
objects:
      track:
        - person
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 1000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.3
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.5
      

# Grabaciones de eventos
record:
  # Guardamos todos los videos?.
  enabled: True
  # Cada cuanto nos fijamos si hay que borrar algun video viejo ocupando espacio?
  expire_interval: 10
  retain: 
    days: 0
    mode: active_objects
  events: 
    retain:
      default: 10
      mode: active_objects
      
      
#Camaras 
cameras:

  track1:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.73
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True

  track3:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.46
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True

  track4:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.59
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True

  track5:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.79
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True

  track6:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.70
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True

  track7:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.81
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True

  track8:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.49
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
       - 250,123,465,127,552,0,212,0
    
  track_nueva:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.100
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 640,0,531,0,558,554,640,640

  track_pozo_frio:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.69
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 179,0,0,0,0,389,177,367
        - 180,0,594,0,506,109,207,39
    
  track_entrada:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.131
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 53,640,561,640,450,492,158,499
        - 424,0,377,112,233,112,175,0
  
  track_salida:
    ffmpeg:
#       hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:2Mini001.@192.168.88.54
          roles:
            - detect #Detecta personas
            - record #Graba el video
    detect:
      enabled: True
    motion:
      mask:
        - 42,437,125,412,121,288,35,269
        - 77,640,640,640,507,498,182,516
        - 388,121,420,0,206,0,249,129
  
  

# Detectores
#detectors:
#  cpu1:
#    type: cpu
#    num_threads: 3

detectors:
  ov1:
    type: openvino
    device: AUTO
    num_threads: 4
    model:
      path: /yolov8/bestYolo8n.xml 
  ov2:
    type: openvino
    device: AUTO
    num_threads: 4
    model:
      path: /yolov8/bestYolo8n.xml
  
      
# Modelos
model:
  width: 640 #416 #704
  height: 640 #416
  input_tensor: nchw #nchw
  input_pixel_format: rgb #bgr #rgb
  model_type: yolov8
  labelmap:
    0: person





